name: Test

on:
  push:
    branch: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn build
      - run: yarn test